package fr.crntech.babyphone.shared

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
enum class Role {
    IDLE, EMITTER, RECEIVER;

    /** Roles that receive the frames sent by this role. */
    val audience: Set<Role>
        get() = when (this) {
            EMITTER -> setOf(RECEIVER)
            RECEIVER -> setOf(EMITTER)
            IDLE -> emptySet()
        }
}

/** End-to-end encrypted messages between devices. The server relays them as opaque bytes. */
@Serializable
sealed interface PeerMessage {
    @Serializable
    @SerialName("status")
    data class EmitterStatus(
        val batteryPercent: Int,
        val charging: Boolean,
        val levelDb: Float,
        val thresholdDb: Float,
        val transmitting: Boolean,
        /** Do-not-disturb on the emitter; null when the platform cannot tell. */
        val quiet: Boolean? = null,
    ) : PeerMessage

    /** 16-bit little-endian mono PCM, see [AudioSpec]. */
    @Serializable
    @SerialName("audio")
    class Audio(val pcm: ByteArray) : PeerMessage

    @Serializable
    @SerialName("threshold")
    data class SetThreshold(val db: Float) : PeerMessage

    /** Keep-alive sent while a receiver holds "listen live"; expires after [Timing.FORCE_LISTEN_TTL]. */
    @Serializable
    @SerialName("force")
    data object ForceListen : PeerMessage
}

@Serializable
data class Peer(val deviceId: String, val name: String, val role: Role)

/** Plain-text events generated by the server itself. */
@Serializable
sealed interface ServerEvent {
    @Serializable
    @SerialName("presence")
    data class Presence(val peers: List<Peer>) : ServerEvent
}

object Wire {
    private val json = Json { ignoreUnknownKeys = true }

    fun encode(event: ServerEvent): String = json.encodeToString(ServerEvent.serializer(), event)
    fun decode(text: String): ServerEvent? =
        runCatching { json.decodeFromString(ServerEvent.serializer(), text) }.getOrNull()
}

object Endpoints {
    const val SOCKET_PATH = "/ws"
    const val HEALTH_PATH = "/health"
    const val PARAM_DEVICE = "device"
    const val PARAM_NAME = "name"
    const val PARAM_ROLE = "role"

    fun roomSocket(publicUrl: String, roomId: String, peer: Peer): String {
        val base = publicUrl.trimEnd('/').replaceFirst(Regex("^http"), "ws")
        val query = mapOf(PARAM_DEVICE to peer.deviceId, PARAM_NAME to peer.name, PARAM_ROLE to peer.role.name)
            .entries.joinToString("&") { (k, v) -> "$k=${percentEncode(v)}" }
        return "$base$SOCKET_PATH/$roomId?$query"
    }

    private const val UNRESERVED = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"

    private fun percentEncode(value: String) = value.encodeToByteArray().joinToString("") { byte ->
        val char = byte.toInt().toChar()
        if (byte >= 0 && char in UNRESERVED) char.toString() else "%" + byte.toUByte().toString(16).uppercase().padStart(2, '0')
    }
}
