package fr.crntech.babyphone.shared

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
enum class Role {
    IDLE, EMITTER, RECEIVER;

    /** Roles that receive the frames sent by this role; parents also hear each other. */
    val audience: Set<Role>
        get() = when (this) {
            EMITTER -> setOf(RECEIVER)
            RECEIVER -> setOf(EMITTER, RECEIVER)
            IDLE -> emptySet()
        }
}

/**
 * What travels end-to-end encrypted: sender and recipient stay hidden from the server.
 * A null [to] addresses every device the sender's role reaches.
 */
@Serializable
data class Envelope(val from: String, val to: String? = null, val message: PeerMessage)

/** End-to-end encrypted messages between devices. The server relays them as opaque bytes. */
@Serializable
sealed interface PeerMessage {
    @Serializable
    @SerialName("status")
    data class EmitterStatus(
        val batteryPercent: Int,
        val charging: Boolean,
        val levelDb: Float,
        val thresholdDb: Float,
        val transmitting: Boolean,
        /** Do-not-disturb on the emitter; null when the platform cannot tell. */
        val quiet: Boolean? = null,
    ) : PeerMessage

    /** Baby sound, or a parent talking to one baby. 16-bit little-endian mono PCM, see [AudioSpec]. */
    @Serializable
    @SerialName("audio")
    class Audio(val pcm: ByteArray) : PeerMessage

    /** A parent talking to the other parents; babies ignore it. Same format as [Audio]. */
    @Serializable
    @SerialName("intercom")
    class Intercom(val pcm: ByteArray) : PeerMessage

    @Serializable
    @SerialName("threshold")
    data class SetThreshold(val db: Float) : PeerMessage

    /** Keep-alive sent while a receiver holds "listen live"; expires after [Timing.FORCE_LISTEN_TTL]. */
    @Serializable
    @SerialName("force")
    data object ForceListen : PeerMessage

    /** The emitter stops on purpose: the parents forget it instead of raising the lost-link alarm. */
    @Serializable
    @SerialName("leaving")
    data object Leaving : PeerMessage
}

@Serializable
data class Peer(
    val deviceId: String,
    val name: String,
    val role: Role,
    /** [PROTOCOL_VERSION] of the device; 0 for versions that did not announce it (up to 1.0.0). */
    val protocol: Int = 0,
    /** App version, only shown to tell which device to update. */
    val version: String? = null,
) {
    /** Which side must be updated for these two devices to understand each other; null when they do. */
    val outdated: Outdated?
        get() = when {
            protocol == PROTOCOL_VERSION -> null
            protocol < PROTOCOL_VERSION -> Outdated.PEER
            else -> Outdated.SELF
        }
}

enum class Outdated { PEER, SELF }

/** Bumped whenever devices of different versions can no longer understand each other. */
const val PROTOCOL_VERSION = 1

/** Plain-text events generated by the server itself. */
@Serializable
sealed interface ServerEvent {
    @Serializable
    @SerialName("presence")
    data class Presence(val peers: List<Peer>) : ServerEvent
}

object Wire {
    private val json = Json { ignoreUnknownKeys = true }

    fun encode(event: ServerEvent): String = json.encodeToString(ServerEvent.serializer(), event)
    fun decode(text: String): ServerEvent? =
        runCatching { json.decodeFromString(ServerEvent.serializer(), text) }.getOrNull()
}

object Endpoints {
    const val SOCKET_PATH = "/ws"
    const val HEALTH_PATH = "/health"
    const val PARAM_DEVICE = "device"
    const val PARAM_NAME = "name"
    const val PARAM_ROLE = "role"
    const val PARAM_PROTOCOL = "protocol"
    const val PARAM_VERSION = "version"

    fun roomSocket(publicUrl: String, roomId: String, peer: Peer): String {
        val base = publicUrl.trimEnd('/').replaceFirst(Regex("^http"), "ws")
        val params = mapOf(
            PARAM_DEVICE to peer.deviceId,
            PARAM_NAME to peer.name,
            PARAM_ROLE to peer.role.name,
            PARAM_PROTOCOL to peer.protocol.toString(),
            PARAM_VERSION to peer.version,
        )
        val query = params.mapNotNull { (k, v) -> v?.let { "$k=${percentEncode(it)}" } }.joinToString("&")
        return "$base$SOCKET_PATH/$roomId?$query"
    }

    private const val UNRESERVED = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"

    private fun percentEncode(value: String) = value.encodeToByteArray().joinToString("") { byte ->
        val char = byte.toInt().toChar()
        if (byte >= 0 && char in UNRESERVED) char.toString() else "%" + byte.toUByte().toString(16).uppercase().padStart(2, '0')
    }
}
